### ISSUE TITLE
purpose of this?

### ISSUE THREAD

**Issue by ORESoftware** [71104/rwlock#8]
This looks to only work for a single process? I don't see any i/o routines in the library.
Since node.js is single-threaded, why do we need a lock for a single process?

**Comment by 71104** [comment]
Node.js is single threaded but asynchronous APIs and promises allow to delay the execution of the rest of a routine so that other routines may run in the meantime. This module allows one to prevent other routines from messing up with your state if you have any.

**Comment by ORESoftware** [comment]
True, you do need a way to synchronize things, even in a single-process.
